name: Get Activation File
on: workflow_dispatch
jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request activation file
        # On utilise directement la branche principale pour éviter les erreurs de version
        uses: game-ci/unity-request-activation-file@main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: registration-file
          path: ./*.alf
